### ISSUE TITLE
运行报错，求解答

### ISSUE THREAD

**Issue by mayjack0312** [shixiangkuangmo/meituan#8]
本地运行日常报错，求解答
```
node .\meituan25_12_10_30.js
0
1
C:\Users\LMY\Downloads\meituan-main\mt\meituan25_12_10_30.js:193
        let userId = cookieStr.match(/userId=(\d+)/)[1];
                                                    ^

TypeError: Cannot read properties of null (reading '1')
    at C:\Users\LMY\Downloads\meituan-main\mt\meituan25_12_10_30.js:193:53
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.16.1
```
抓包抓的是`https://www.meituan.com/ `里面的`cookie `

**Comment by mayjack0312** [comment]
> 确保ck中包含说明中所描述的字段

是这样吗？
https://github.com/shixiangkuangmo/meituan/issues/8#issuecomment-1765995942

**Comment by shixiangkuangmo** [comment]
> > 确保ck中包含说明中所描述的字段
> 
> 是这样吗？ ![image](https://user-images.githubusercontent.com/102800660/275777985-dbdbe815-6353-41c6-bdf6-0bcd5b5c9f72.png)

缺userId字段

**Comment by mayjack0312** [comment]
> > > 确保ck中包含说明中所描述的字段
> > 
> > 
> > 是这样吗？ ![image](https://user-images.githubusercontent.com/102800660/275777985-dbdbe815-6353-41c6-bdf6-0bcd5b5c9f72.png)
> 
> 缺userId字段

抓到了，从url里抓到的，现在是这个情况  
![image](https://github.com/shixiangkuangmo/meituan/assets/102800660/f3ee094b-a5d9-4eaf-80a7-15acdc6be7c4)

**Comment by shixiangkuangmo** [comment]
> Au
请求失败

**Comment by mayjack0312** [comment]
> > Au
> > 请求失败

是网络的问题吗？还是过时造成的？
我放到青龙里去明天按时运行是不是就会好了呀 ^_^

**Comment by shixiangkuangmo** [comment]
> > > Au
> > > 请求失败
> 
> 是网络的问题吗？还是过时造成的？ 我放到青龙里去明天按时运行是不是就会好了呀 ^_^

看着像是请求某个https网址时 报的问题 你可以在青龙运行试试

**Comment by mayjack0312** [comment]
> > > > Au
> > > > 请求失败
> > 
> > 
> > 是网络的问题吗？还是过时造成的？ 我放到青龙里去明天按时运行是不是就会好了呀 ^_^
> 
> 看着像是请求某个https网址时 报的问题 你可以在青龙运行试试

感觉还是有点不对劲
![image](https://github.com/shixiangkuangmo/meituan/assets/102800660/3cbe8479-648f-4810-a43f-2fc79d12477f)

**Comment by mayjack0312** [comment]
感觉还是ck没整对，这个抓ck是网页抓还是小程序抓呀？

**Comment by ackker** [comment]
对，我把这个【1】删掉了，可以跑通，但是运行的时候会提示forbidden @shixiangkuangmo

**Comment by mayjack0312** [comment]
> 对，我把这个【1】删掉了，可以跑通，但是运行的时候会提示forbidden @shixiangkuangmo

有一个美团的WEBDFPID，死活抓不到，不知道用什么能抓到

**Comment by shixiangkuangmo** [comment]
> 对，我把这个【1】删掉了，可以跑通，但是运行的时候会提示forbidden @shixiangkuangmo

是的 目前算法需要升级

**Comment by shixiangkuangmo** [comment]
> > 对，我把这个【1】删掉了，可以跑通，但是运行的时候会提示forbidden @shixiangkuangmo
> 
> 有一个美团的WEBDFPID，死活抓不到，不知道用什么能抓到

浏览器抓的就有 app没试过

**Comment by mayjack0312** [comment]
> > > 对，我把这个【1】删掉了，可以跑通，但是运行的时候会提示forbidden @shixiangkuangmo
> > 
> > 
> > 有一个美团的WEBDFPID，死活抓不到，不知道用什么能抓到
> 
> 浏览器抓的就有 app没试过

浏览器也抓不到，用什么浏览器呀？直接f12吗？

**Comment by shixiangkuangmo** [comment]
> > > > Yes, I deleted this [1], it can run through, but when running, it will prompt forbidden @shixiangkuangmo
> > > 
> > > 
> > > THERE IS A WEBDFPID OF MEITUAN, WHICH CANNOT BE CAUGHT DEAD OR ALIVE, AND DOES NOT KNOW WHAT TO CATCH
> > 
> > 
> > the browser catches the app and has not tried it
> 
> browser can't catch it, what browser do you use? Direct f12?

Android alook右下角长按-开发者工具-复制cookies

**Comment by mayjack0312** [comment]
> > > > > Yes, I deleted this [1], it can run through, but when running, it will prompt forbidden @shixiangkuangmo
> > > > 
> > > > 
> > > > THERE IS A WEBDFPID OF MEITUAN, WHICH CANNOT BE CAUGHT DEAD OR ALIVE, AND DOES NOT KNOW WHAT TO CATCH
> > > 
> > > 
> > > the browser catches the app and has not tried it
> > 
> > 
> > browser can't catch it, what browser do you use? Direct f12?
> 
> Android alook右下角长按-开发者工具-复制cookies

好的，我试试

**Comment by shixiangkuangmo** [comment]
> > > > > > Yes, I deleted this [1], it can run through, but when running, it will prompt forbidden @shixiangkuangmo
> > > > > 
> > > > > 
> > > > > THERE IS A WEBDFPID OF MEITUAN, WHICH CANNOT BE CAUGHT DEAD OR ALIVE, AND DOES NOT KNOW WHAT TO CATCH
> > > > 
> > > > 
> > > > the browser catches the app and has not tried it
> > > 
> > > 
> > > browser can't catch it, what browser do you use? Direct f12?
> > 
> > 
> > Android alook右下角长按-开发者工具-复制cookies
> 
> 我用Android alook抓包，抓下来还是提示报错 ![image](https://user-images.githubusercontent.com/102800660/276203122-b607787e-c3a4-4013-ba33-661ed80be0d6.png) ![fa7d6ef42247d9b96edc430cfff6b29](https://user-images.githubusercontent.com/102800660/276203216-75a51fd1-a542-452b-9baa-ee0c7c98f487.jpg) 坐等大佬更新

这个是检测ck时 检测到ck失效进行删除时报错的 应该是没配置青龙的账号和密码

**Comment by mayjack0312** [comment]
> > > > > > > Yes, I deleted this [1], it can run through, but when running, it will prompt forbidden @shixiangkuangmo
> > > > > > 
> > > > > > 
> > > > > > THERE IS A WEBDFPID OF MEITUAN, WHICH CANNOT BE CAUGHT DEAD OR ALIVE, AND DOES NOT KNOW WHAT TO CATCH
> > > > > 
> > > > > 
> > > > > the browser catches the app and has not tried it
> > > > 
> > > > 
> > > > browser can't catch it, what browser do you use? Direct f12?
> > > 
> > > 
> > > Android alook右下角长按-开发者工具-复制cookies
> > 
> > 
> > 我用Android alook抓包，抓下来还是提示报错 ![image](https://user-images.githubusercontent.com/102800660/276203122-b607787e-c3a4-4013-ba33-661ed80be0d6.png) ![fa7d6ef42247d9b96edc430cfff6b29](https://user-images.githubusercontent.com/102800660/276203216-75a51fd1-a542-452b-9baa-ee0c7c98f487.jpg) 坐等大佬更新
> 
> 这个是检测ck时 检测到ck失效进行删除时报错的 应该是没配置青龙的账号和密码

求个详细解答，感觉还是抓包没抓对，这个抓的是www.meituan.com的包吗？怎么一直找不到WEBDFPID呀？
